version: 2.1

jobs:
  build_androidTest_unitTest:
    machine:
      image: android:202102-01
    resource_class: large
    #    environment:
    #      JVM_OPTS: -Xmx4096m
    steps:
      - checkout

      - run:
          name: setup local.properties
          command: |
            echo debug_store_password="$DEBUG_STORE_PASSWORD" >> local.properties
            echo debug_key_alias="$DEBUG_KEY_ALIAS" >> local.properties
            echo debug_key_password="$DEBUG_KEY_PASSWORD" >> local.properties
            echo debug_store_file=~/debug.keystore >> local.properties

            echo release_store_password="$RELEASE_STORE_PASSWORD" >> local.properties
            echo release_key_alias="$RELEASE_KEY_ALIAS" >> local.properties
            echo release_key_password="$RELEASE_KEY_PASSWORD" >> local.properties
            echo release_store_file=~/release.keystore >> local.properties

      - run:
          name: generate key store
          command: |
            echo "$DEBUG_STORE_FILE_ASC_BASE64" | base64 --decode > ~/debug.keystore.jks.asc
            gpg -d --passphrase $DEBUG_STORE_FILE_ASC_BASE64_PASSPHRASE --batch ~/debug.keystore.jks.asc > ~/debug.keystore

            echo "$RELEASE_STORE_FILE_ASC_BASE64" | base64 --decode > ~/release.keystore.jks.asc
            gpg -d --passphrase $RELEASE_STORE_FILE_ASC_BASE64_PASSPHRASE --batch ~/release.keystore.jks.asc > ~/release.keystore

      - run:
          name: create avd
          command: |
            SYSTEM_IMAGES="system-images;android-30;google_apis;x86"
            sdkmanager "$SYSTEM_IMAGES"
            echo "no" | avdmanager --verbose create avd -n test -k "$SYSTEM_IMAGES"

      - run:
          name: launch emulator
          command: |
            emulator -avd test -delay-adb -verbose -no-window -noaudio -no-boot-anim -memory 4096 -accel on -qemu -enable-kvm
          background: true

      - run:
          name: genarate cache key
          command: |
            find . -name 'build.gradle' | sort | xargs cat |
            shasum | awk '{print $1}' > /tmp/gradle_cache_seed

      - restore_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}

      - run:
          name: replace org.gradle.jvmargs in gradle properties
          command: |
            ORG_GRADLE_JVM=`cat gradle.properties | grep org.gradle.jvmargs`
            sed -i 's/'"${ORG_GRADLE_JVM}"'/org.gradle.jvmargs=-Xmx8192m -Dfile.encoding=UTF-8/g' gradle.properties
            cat gradle.properties | grep org.gradle.jvmargs

      - run:
          name: install cmake 3.18.1
          command: sdkmanager "cmake;3.18.1"

      - run:
          name: gradlew download dependencies
          command: ./gradlew androidDependencies

      - save_cache:
          key: gradle-v0-{{ arch }}-{{ checksum "/tmp/gradle_cache_seed" }}
          paths:
            - ~/.gradle

      - run:
          name: gradle clean build
          command: ./gradlew clean build

      - run:
          name: wait for emulator to start
          command: circle-android wait-for-boot

      - run:
          name: disable emulator animations and close system dialog
          command: |
            adb shell settings put global window_animation_scale 0.0
            adb shell settings put global transition_animation_scale 0.0
            adb shell settings put global animator_duration_scale 0.0
            adb shell am broadcast -a android.intent.action.CLOSE_SYSTEM_DIALOGS
            # Send keystroke Arrow Right
            sleep 3; adb shell input keyevent 22
            # Send keystroke Arrow Right again
            sleep 3; adb shell input keyevent 22
            # Send keystroke Enter to press a button on the dialog
            sleep 3; adb shell input keyevent 66
            adb shell input keyevent 82

      - run:
          name: gradle connected android test
          command: |
            MAX_TRIES=2
            run_with_retry() {
               n=1
               until [ $n -gt $MAX_TRIES ]
               do
                  echo "Starting test attempt $n"
                  ./gradlew connectedAndroidTest && break
                  n=$[$n+1]
                  sleep 5
               done
               if [ $n -gt $MAX_TRIES ]; then
                 echo "Max tries reached ($MAX_TRIES)"
                 exit 1
               fi
            }
            run_with_retry

      - run:
          name: gradle unit test
          command: ./gradlew test

      - store_artifacts:
          path: app/build/reports
          destination: reports

      - store_artifacts:
          path: app/build/outputs
          destination: outputs

      - store_artifacts:
          path: app/build/intermediates/cmake
          destination: cmake

      - store_test_results:
          path: app/build/test-results

workflows:
  build:
    jobs:
      - build_androidTest_unitTest:
          context:
            - android-key-store